language: node_js
os:
  - windows
  - linux
node_js:
  - "8"
sudo: false
# addons:
#   chrome: stable
#   firefox: latest
# before_script:
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
script:
  # - npm --silent run deploy-set-version -- --buildVersion $TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER
  # - npm --silent run deploy-status -- --status pending --message 'Waiting for build'

  # - npm --silent run eslint

  - npm --silent run build
  - npm --silent run test -- --browsers Edge --webgl-stub --failTaskOnError --suppressPassed

  # - npm --silent run clean
  # - travis_wait 20 npm --silent run makeZipFile -- --concurrency 1
  # - npm pack &> /dev/null

  # - npm --silent run buildApps

  # - npm --silent run deploy-s3 -- -b cesium-dev -d cesium/$TRAVIS_BRANCH --confirm -c 'no-cache'
  # - npm --silent run deploy-status -- --status success --message Deployed

  # - npm --silent run test -- --browsers ChromeCI --failTaskOnError --webgl-stub --release --suppressPassed

  # - node index.js

  # - npm --silent run cloc
